name: "Sonar Quality Gate for windows and linux"
description: "Run SonarQube quality gate check"

inputs:
  sonar_host_url:
    description: "SonarQube Host URL"
    required: true
  sonar_token:
    description: "SonarQube API Token"
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Run on Windows
      if: runner.os == 'windows'
      shell: powershell
      run: |
        scripts/windows.ps1
      env:
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}

    - name: Run on Linux / macOS
      if: runner.os != 'windows'
      shell: bash
      run: |
        bash scripts/linux.sh
      env:
        SONAR_HOST_URL: ${{ inputs.sonar_host_url }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
