#Composite Action = Reusable group of steps packaged as one action
#actions/setup-java sets up Java for workflow steps, not the VM globally
#Composite actions are step-level reusable units

name: "Setup java App"

inputs:
  java-version:
    description: "java version version"
    required: true

runs:
  using: "composite"
  steps:
    - name: setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: ${{ inputs.java-version}}


