name: resusable_action
description: Prints a hello message
inputs:
  name:
    required: true
    type: string

runs:
  # It tells GitHub that your custom action is a composite action, which is:
  # A group of shell commands or other steps combined into a reusable unit.
  using: "composite"
  steps:
    - run: echo "Hello ${{ inputs.name }}"