name: artifacts_upload
on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  artifact_upload:
    runs-on: ubuntu-latest
    steps:
    - name: checking out
      uses: actions/checkout@v4
    - name: uploading artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.ARTIFACT_NAME}}
        path: . #This step uploads everything in the current directory

