on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["testaction"]
    types:
      - completed
jobs:
  dependent_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: second workflow
      run: echo "this is executing after testaction workflow"
    - name: printing github hash
      run: echo "printing github hash id $GITHUB_SHA"
      shell: bash
      # Calling action.yaml from actions folder in our repository
    - name: calling action.yaml
      uses: ./actions
      with: # Passing arguments to action
       name: "Manikanta"