on:
  workflow_run:
    workflows: ["testaction"]
    types:
      - completed
jobs:
  dependent_job:
    runs-on: ubuntu-latest
    steps:
    - name: second workflow
      run: echo "this is test workflow2"
    

